var app = angular.module("HueMeApp");
app.service('countryService', function() {
  this.countries = [
    "Afghanistan",
    "Åland Islands",
    "Albania",
    "Algeria",
    "American Samoa",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antarctica",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bonaire, Sint Eustatius and Saba",
    "Bosnia and Herzegovina",
    "Botswana",
    "Bouvet Island",
    "Brazil",
    "British Indian Ocean Territory",
    "Brunei Darussalam",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Cayman Islands",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Christmas Island",
    "Cocos (Keeling) Islands",
    "Colombia",
    "Comoros",
    "Congo, Republic of the (Brazzaville)",
    "Congo, the Democratic Republic of the (Kinshasa)",
    "Cook Islands",
    "Costa Rica",
    "Côte d'Ivoire, Republic of",
    "Croatia",
    "Cuba",
    "Curaçao",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Falkland Islands (Islas Malvinas)",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "France",
    "French Guiana",
    "French Polynesia",
    "French Southern and Antarctic Lands",
    "Gabon",
    "Gambia, The",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Heard Island and McDonald Islands",
    "Holy See (Vatican City)",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran, Islamic Republic of",
    "Iraq",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Korea, Democratic People's Republic of",
    "Korea, Republic of",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macao",
    "Macedonia, Former Yugoslav Republic of",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Martinique",
    "Mauritania",
    "Mauritius",
    "Mayotte",
    "Mexico",
    "Micronesia, Federated States of",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Niue",
    "Norfolk Island",
    "Northern Mariana Islands",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine, State of",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Pitcairn",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Réunion",
    "Romania",
    "Russian Federation",
    "Rwanda",
    "Saint Barthélemy",
    "Saint Helena, Ascension and Tristan da Cunha",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Martin (French part)",
    "Saint Pierre and Miquelon",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Sint Maarten (Dutch part)",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Georgia and South Sandwich Islands",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Svalbard and Jan Mayen",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syrian Arab Republic",
    "Taiwan, Province of China",
    "Tajikistan",
    "Tanzania, United Republic of",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Turks and Caicos Islands",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United Kingdom Overseas Territories",
    "United States",
    "United States Minor Outlying Islands",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela, Bolivarian Republic of",
    "Viet Nam",
    "Virgin Islands, British",
    "Virgin Islands, U.S.",
    "Wallis and Futuna",
    "Western Sahara",
    "Yemen",
    "Zambia",
    "Zimbabwe"
  ];

  this.regions = {
    "Afghanistan":[ "Badakhshan", "Badghis", "Baghlan", "Balkh", "Bamyan", "Daykundi", "Farah", "Faryab", "Ghazni", "Ghor", "Helmand", "Herat", "Jowzjan", "Kabul", "Kandahar", "Kapisa", "Khost", "Kunar", "Kunduz", "Laghman", "Logar", "Maidan Wardak", "Nangarhar", "Nimruz", "Nuristan", "Paktia", "Paktika", "Panjshir", "Parwan", "Samangan", "Sar-e Pol", "Takhar", "Urozgan", "Zabul"],
    "Åland Islands":[ "Brändö", "Eckerö", "Finström", "Föglö", "Geta", "Hammarland", "Jomala", "Kumlinge", "Kökar", "Lemland", "Lumparland", "Mariehamn", "Saltvik", "Sottunga", "Sund", "Vårdö"],
    "Albania":[ "Berat", "Dibër", "Durrës", "Elbasan", "Fier", "Gjirokastër", "Korçë", "Kukës", "Lezhë", "Shkodër", "Tirana", "Vlorë"],
    "Algeria":[ "Adrar", "Aïn Defla", "Aïn Témouchent", "Algiers", "Annaba", "Batna", "Béchar", "Béjaïa", "Biskra", "Blida", "Bordj Bou Arréridj", "Bouïra", "Boumerdès", "Chlef", "Constantine", "Djelfa", "El Bayadh", "El Oued", "El Tarf", "Ghardaïa", "Guelma", "Illizi", "Jijel", "Khenchela", "Laghouat", "Mascara", "Médéa", "Mila", "Mostaganem", "Msila", "Naâma", "Oran", "Ouargla", "Oum el Bouaghi", "Relizane", "Saïda", "Sétif", "Sidi Bel Abbès", "Skikda", "Souk Ahras", "Tamanghasset", "Tébessa", "Tiaret", "Tindouf", "Tipaza", "Tissemsilt", "Tizi Ouzou", "Tlemcen"],
    "American Samoa":[ "Tutuila", "Aunu'u", "Ta'ū", "Ofu‑Olosega", "Rose Atoll", "Swains Island"],
    "Andorra":[ "Andorra la Vella", "Canillo", "Encamp", "Escaldes-Engordany", "La Massana", "Ordino", "Sant Julià de Lòria"],
    "Angola":[ "Bengo", "Benguela", "Bié", "Cabinda", "Cuando Cubango", "Cuanza Norte", "Cuanza Sul", "Cunene", "Huambo", "Huíla", "Luanda", "Lunda Norte", "Lunda Sul", "Malanje", "Moxico", "Namibe", "Uíge", "Zaire"],
    "Anguilla":[ "Anguilla", "Anguillita Island", "Blowing Rock", "Cove Cay", "Crocus Cay", "Deadman's Cay", "Dog Island", "East Cay", "Little Island", "Little Scrub Island", "Mid Cay", "North Cay", "Prickly Pear Cays", "Rabbit Island", "Sandy Island/Sand Island", "Scilly Cay", "Scrub Island", "Seal Island", "Sombrero/Hat Island", "South Cay", "South Wager Island", "West Cay"],
    "Antarctica":[ "Antarctica"],
    "Antigua and Barbuda":[ "Antigua Island", "Barbuda Island", "Bird Island", "Bishop Island", "Blake Island", "Crump Island", "Dulcina Island", "Exchange Island", "Five Islands", "Great Bird Island", "Green Island", "Guiana Island", "Hawes Island", "Hells Gate Island", "Henry Island", "Johnson Island", "Kid Island", "Lobster Island", "Maiden Island", "Moor Island", "Nanny Island", "Pelican Island", "Prickly Pear Island", "Rabbit Island", "Red Head Island", "Redonda Island", "Sandy Island", "Smith Island", "The Sisters", "Vernon Island", "Wicked Will Island", "York Island"],
    "Argentina":[ "Buenos Aires", "Capital Federal", "Catamarca", "Chaco", "Chubut", "Córdoba", "Corrientes", "Entre Ríos", "Formosa", "Jujuy", "La Pampa", "La Rioja", "Mendoza", "Misiones", "Neuquén", "Río Negro", "Salta", "San Juan", "San Luis", "Santa Cruz", "Santa Fe", "Santiago del Estero", "Tierra del Fuego", "Tucumán"],
    "Armenia":[ "Aragatsotn", "Ararat", "Armavir", "Gegharkunik", "Kotayk", "Lori", "Shirak", "Syunik", "Tavush", "Vayots Dzor", "Yerevan"],
    "Aruba":[ "Aruba"],
    "Australia":[ "Australian Capital Territory", "New South Wales", "Northern Territory", "Queensland", "South Australia", "Tasmania", "Victoria", "Western Australia"],
    "Austria":[ "Burgenland", "Kärnten", "Niederösterreich", "Oberösterreich", "Salzburg", "Steiermark", "Tirol", "Vorarlberg", "Wien"],
    "Azerbaijan":[ "Bakı", "Gəncə", "Lənkəran", "Mingəçevir", "Naftalan", "Naxçıvan", "Şəki", "Şirvan", "Sumqayit", "Xankəndi", "Yevlax", "Abşeron", "Ağcabədi", "Ağdam", "Ağdaş", "Ağstafa", "Ağsu", "Astara", "Babək", "Balakən", "Bərdə", "Beyləqan", "Biləsuvar", "Cəbrayıl", "Cəlilabad", "Culfa", "Daşkəsən", "Füzuli", "Gədəbəy", "Goranboy", "Göyçay", "Göygöl", "Hacıqabul", "İmişli", "İsmayıllı", "Kəlbəcər", "Kǝngǝrli", "Kürdəmir", "Laçın", "Lənkəran", "Lerik", "Masallı", "Neftçala", "Oğuz", "Ordubad", "Qəbələ", "Qax", "Qazax", "Qobustan", "Quba", "Qubadli", "Qusar", "Saatlı", "Sabirabad", "Şabran", "Sədərək", "Şahbuz", "Şəki", "Salyan", "Şamaxı", "Şəmkir", "Samux", "Şərur", "Siyəzən", "Şuşa", "Tərtər", "Tovuz", "Ucar", "Xaçmaz", "Xızı", "Xocalı", "Xocavənd", "Yardımlı", "Yevlax", "Zəngilan", "Zaqatala", "Zərdab"],
    "Bahamas":[ "Acklins Island", "Berry Islands", "Bimini", "Black Point", "Cat Island", "Central Abaco", "Crooked Island and Long Cay", "East Grand Bahama", "Exuma", "Freeport", "Fresh Creek", "Governor's Harbour", "Green Turtle Cay", "Harbour Island", "High Rock", "Inagua", "Kemps Bay", "Long Island", "Marsh Harbour", "Mayaguana", "Moore’s Island", "New Providence", "Nichollstown and Berry Islands", "North Abaco", "North Andros", "North Eleuthera", "Ragged Island", "Rock Sound", "San Salvador and Rum Cay", "Sandy Point", "South Abaco", "South Andros", "South Eleuthera", "West Grand Bahama"],
    "Bahrain":[ "Al Janūbīyah", "Al Manāmah", "Al Muḩarraq", "Al Wusţá", "Ash Shamālīyah"],
    "Bangladesh":[ "Barisal", "Chittagong", "Dhaka", "Khulna", "Rajshahi", "Rangpur", "Sylhet"],
    "Barbados":[ "Christ Church", "Saint Andrew", "Saint George", "Saint James", "Saint John", "Saint Joseph", "Saint Lucy", "Saint Michael", "Saint Peter", "Saint Philip", "Saint Thomas"],
    "Belarus":[ "Brest voblast", "Gorod Minsk", "Homiel voblast", "Hrodna voblast", "Mahilyow voblast", "Minsk voblast", "Vitsebsk voblast"],
    "Belgium":[ "Bruxelles-Capitale", "Région Flamande", "Région Wallonië"],
    "Belize":[ "Belize District", "Cayo District", "Corozal District", "Orange Walk District", "Stann Creek District", "Toledo District"],
    "Benin":[ "Alibori", "Atakora", "Atlantique", "Borgou", "Collines Department", "Donga", "Kouffo", "Littoral Department", "Mono Department", "Ouémé", "Plateau", "Zou"],
    "Bermuda":[ "City of Hamilton", "Devonshire Parish", "Hamilton Parish", "Paget Parish", "Pembroke Parish", "Sandys Parish", "Smith's Parish", "Southampton Parish", "St. George's Parish", "Town of St. George", "Warwick Parish"],
    "Bhutan":[ "Bumthang", "Chhukha", "Dagana", "Gasa", "Haa", "Lhuntse", "Mongar", "Paro", "Pemagatshel", "Punakha", "Samdrup Jongkhar", "Samtse", "Sarpang", "Thimphu", "Trashigang", "Trashiyangtse", "Trongsa", "Tsirang", "Wangdue Phodrang", "Zhemgang"],
    "Bolivia":[ "Beni", "Chuquisaca", "Cochabamba", "La Paz", "Oruro", "Pando", "Potosí", "Santa Cruz", "Tarija"],
    "Bonaire, Sint Eustatius and Saba":[ "Bonaire", "Saba Isand", "Sint Eustatius"],
    "Bosnia and Herzegovina":[ "Brčko Distrikt", "Federacija Bosne i Hercegovine", "Republika Srpska"],
    "Botswana":[ "Central", "Ghanzi", "Kgalagadi", "Kgatleng", "Kweneng", "North West", "North-East", "South East", "Southern"],
    "Bouvet Island":[ "Bouvet Island"],
    "Brazil":[ "Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Distrito Federal", "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Para", "Paraiba", "Paraná", "Pernambuco", "Piauí", "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia", "Roraima", "Santa Catarina", "Sao Paulo", "Sergipe", "Tocantins"],
    "British Indian Ocean Territory":[ "British Indian Ocean Territory"],
    "Brunei Darussalam":[ "Belait", "Brunei Muara", "Temburong", "Tutong"],
    "Bulgaria":[ "Blagoevgrad", "Burgas", "Dobrich", "Gabrovo", "Jambol", "Khaskovo", "Kjustendil", "Kurdzhali", "Lovech", "Montana", "Pazardzhik", "Pernik", "Pleven", "Plovdiv", "Razgrad", "Ruse", "Shumen", "Silistra", "Sliven", "Smoljan", "Sofija", "Sofija-Grad", "Stara Zagora", "Turgovishhe", "Varna", "Veliko Turnovo", "Vidin", "Vraca"],
    "Burkina Faso":[ "Balé", "Bam/Lake Bam", "Banwa Province", "Bazèga", "Bougouriba", "Boulgou Province", "Boulkiemdé", "Comoé/Komoe", "Ganzourgou Province", "Gnagna", "Gourma Province", "Houet", "Ioba", "Kadiogo", "Kénédougou", "Komondjari", "Kompienga", "Kossi Province", "Koulpélogo", "Kouritenga", "Kourwéogo", "Léraba", "Loroum", "Mouhoun", "Namentenga", "Naouri/Nahouri", "Nayala", "Noumbiel", "Oubritenga", "Oudalan", "Passoré", "Poni", "Sanguié", "Sanmatenga", "Séno", "Sissili", "Soum", "Sourou", "Tapoa", "Tui/Tuy", "Yagha", "Yatenga", "Ziro", "Zondoma", "Zoundwéogo"],
    "Burundi":[ "Bubanza", "Bujumbura Mairie", "Bujumbura Rural", "Bururi", "Cankuzo", "Cibitoke", "Gitega", "Karuzi", "Kayanza", "Kirundo", "Makamba", "Muramvya", "Muyinga", "Mwaro", "Ngozi", "Rutana", "Ruyigi"],
    "Cambodia":[ "Banteay Mean Cheay", "Batdambang", "Kampong Cham", "Kampong Chhnang", "Kampong Spoe", "Kampong Thum", "Kampot", "Kandal", "Kaoh Kong", "Keb", "Kracheh", "Mondol Kiri", "Otdar Mean Cheay", "Pailin", "Phnum Penh", "Pouthisat", "Preah Seihanu (Sihanoukville)", "Preah Vihear", "Prey Veng", "Rotanah Kiri", "Siem Reab", "Stoeng Treng", "Svay Rieng", "Takev"],
    "Cameroon":[ "Adamaoua", "Centre", "Est", "Extrême-Nord", "Littoral", "Nord", "Nord-Ouest", "Ouest", "Sud", "Sud-Ouest"],
    "Canada":[ "Alberta", "British Columbia", "Manitoba", "New Brunswick", "Newfoundland and Labrador", "Northwest Territories", "Nova Scotia", "Nunavut", "Ontario", "Prince Edward Island", "Quebec", "Saskatchewan", "Yukon"],
    "Cape Verde":[ "Boa Vista", "Brava", "Calheta de São Miguel", "Maio", "Mosteiros", "Paúl", "Porto Novo", "Praia", "Ribeira Brava", "Ribeira Grande", "Sal", "Santa Catarina", "Santa Cruz", "São Domingos", "São Filipe", "São Nicolau", "São Vicente", "Tarrafal", "Tarrafal de São Nicolau"],
    "Cayman Islands":[ "Creek", "Eastern", "Midland", "South Town", "Spot Bay", "Stake Bay", "West End", "Western"],
    "Central African Republic":[ "Bamingui-Bangoran", "Bangui", "Basse-Kotto", "Haute-Kotto", "Haut-Mbomou", "Kémo", "Lobaye", "Mambéré-Kadéï", "Mbomou", "Nana-Grebizi", "Nana-Mambéré", "Ombella-M'Poko", "Ouaka", "Ouham", "Ouham Péndé", "Sangha-Mbaéré", "Vakaga"],
    "Chad":[ "Batha", "Biltine", "Borkou-Ennedi-Tibesti", "Chari-Baguirmi", "Guera", "Kanem", "Lac", "Logone Occidental", "Logone Oriental", "Mayo-Kebbi", "Moyen-Chari", "Ouaddai", "Salamat", "Tandjile"],
    "Chile":[ "Aisén del General Carlos Ibáñez del Campo", "Antofagasta", "Araucanía", "Arica y Parinacota", "Atacama", "Bío-Bío", "Coquimbo", "Libertador General Bernardo O'Higgins", "Los Lagos", "Los Ríos", "Magallanes y Antartica Chilena", "Marga-Marga", "Maule", "Región Metropolitana de Santiago", "Tarapacá", "Valparaíso"],
    "China":[ "Anhui", "Beijing", "Chongqing", "Fujian", "Gansu", "Guangdong", "Guangxi", "Guizhou", "Hainan", "Hebei", "Heilongjiang", "Henan", "Hong Kong", "Hubei", "Hunan", "Inner Mongolia", "Jiangsu", "Jiangxi", "Jilin", "Liaoning", "Macau", "Ningxia", "Qinghai", "Shaanxi", "Shandong", "Shanghai", "Shanxi", "Sichuan", "Tianjin", "Tibet", "Xinjiang", "Yunnan", "Zhejiang"],
    "Christmas Island":[ "Christmas Island"],
    "Cocos (Keeling) Islands":[ "Direction Island", "Home Island", "Horsburgh Island", "North Keeling Island", "South Island", "West Island"],
    "Colombia":[ "Amazonas", "Antioquia", "Arauca", "Archipiélago de San Andrés", "Atlántico", "Bogotá D.C.", "Bolívar", "Boyacá", "Caldas", "Caquetá", "Casanare", "Cauca", "Cesar", "Chocó", "Córdoba", "Cundinamarca", "Guainía", "Guaviare", "Huila", "La Guajira", "Magdalena", "Meta", "Nariño", "Norte de Santander", "Putumayo", "Quindío", "Risaralda", "Santander", "Sucre", "Tolima", "Valle del Cauca", "Vaupés", "Vichada"],
    "Comoros":[ "Anjouan (Nzwani)", "Domoni", "Fomboni", "Grande Comore (Njazidja)", "Moheli (Mwali)", "Moroni", "Moutsamoudou"],
    "Congo, Republic of the (Brazzaville)":[ "Bouenza", "Brazzaville", "Cuvette", "Cuvette-Ouest", "Kouilou", "Lékoumou", "Likouala", "Niari", "Plateaux", "Pointe-Noire", "Pool", "Sangha"],
    "Congo, the Democratic Republic of the (Kinshasa)":[ "Bandundu", "Bas-Congo", "Équateur", "Kasaï-Occidental", "Kasaï-Oriental", "Katanga", "Kinshasa", "Maniema", "Nord-Kivu", "Orientale", "Sud-Kivu"],
    "Cook Islands":[ "Aitutaki", "Atiu", "Avarua", "Mangaia", "Manihiki", "Manuae", "Mauke", "Mitiaro", "Nassau Island", "Palmerston", "Penrhyn", "Pukapuka", "Rakahanga", "Rarotonga", "Suwarrow", "Takutea"],
    "Costa Rica":[ "Alajuela", "Cartago", "Guanacaste", "Heredia", "Limón", "Puntarenas", "San José"],
    "Côte d'Ivoire, Republic of":[ "Agnéby", "Bafing", "Bas-Sassandra", "Denguélé", "Dix-Huit Montagnes", "Fromager", "Haut-Sassandra", "Lacs", "Lagunes", "Marahoué", "Moyen-Cavally", "Moyen-Comoé", "N'zi-Comoé", "Savanes", "Sud-Bandama", "Sud-Comoé", "Vallée du Bandama", "Worodougou", "Zanzan"],
    "Croatia":[ "Bjelovarsko-Bilogorska Zupanija", "Brodsko-Posavska Zupanija", "Dubrovacko-Neretvanska Zupanija", "Istarska Zupanija", "Karlovacka Zupanija", "Koprivnicko-Krizevacka Zupanija", "Krapinsko-Zagorska Zupanija", "Licko-Senjska Zupanija", "Medimurska Zupanija", "Osjecko-Baranjska Zupanija", "Pozesko-Slavonska Zupanija", "Primorsko-Goranska Zupanija", "Sibensko-Kninska Zupanija", "Sisacko-Moslavacka Zupanija", "Splitsko-Dalmatinska Zupanija", "Varazdinska Zupanija", "Viroviticko-Podravska Zupanija", "Vukovarsko-Srijemska Zupanija", "Zadarska Zupanija", "Zagreb", "Zagrebacka Zupanija"],
    "Cuba":[ "Artemisa", "Camagüey", "Ciego de Ávila", "Cienfuegos", "Granma", "Guantánamo", "Holguín", "Isla de la Juventud", "La Habana", "Las Tunas", "Matanzas", "Mayabeque", "Pinar del Río", "Sancti Spíritus", "Santiago de Cuba", "Villa Clara"],
    "Curaçao":[ "Curaçao"],
    "Cyprus":[ "Ammochostos", "Keryneia", "Larnaka", "Lefkosia", "Lemesos", "Pafos"],
    "Czech Republic":[ "Hlavní město Praha", "Jihočeský kraj", "Jihomoravský kraj", "Karlovarský kraj", "Královéhradecký kraj", "Liberecký kraj", "Moravskoslezský kraj", "Olomoucký kraj", "Pardubický kraj", "Plzeňský kraj", "Středočeský kraj", "Ústecký kraj", "Vysočina", "Zlínský kraj"],
    "Denmark":[ "Hovedstaden", "Kujalleq", "Midtjylland", "Norderøerne", "Nordjylland", "Østerø", "Qaasuitsup", "Qeqqata", "Sandø", "Sermersooq", "Sjælland", "Strømø", "Suderø", "Syddanmark", "Vågø"],
    "Djibouti":[ "Ali Sabieh", "Arta", "Dikhil", "Obock", "Tadjourah"],
    "Dominica":[ "Saint Andrew Parish", "Saint David Parish", "Saint George Parish", "Saint John Parish", "Saint Joseph Parish", "Saint Luke Parish", "Saint Mark Parish", "Saint Patrick Parish", "Saint Paul Parish", "Saint Peter Parish"],
    "Dominican Republic":[ "Cibao Central", "Del Valle", "Distrito Nacional", "Enriquillo", "Norcentral", "Nordeste", "Noroeste", "Norte", "Valdesia"],
    "Ecuador":[ "Azuay", "Bolívar", "Cañar", "Carchi", "Chimborazo", "Cotopaxi", "El Oro", "Esmeraldas", "Galápagos", "Guayas", "Imbabura", "Loja", "Los Ríos", "Manabí", "Morona-Santiago", "Napo", "Orellana", "Pastaza", "Pichincha", "Santa Elena", "Santo Domingo de los Tsáchilas", "Sucumbíos", "Tungurahua", "Zamora-Chinchipe"],
    "Egypt":[ "Alexandria", "Aswan", "Asyout", "Bani Sueif", "Beheira", "Cairo", "Daqahlia", "Dumiat", "El Bahr El Ahmar", "El Ismailia", "El Suez", "El Wadi El Gedeed", "Fayoum", "Gharbia", "Giza", "Helwan", "Kafr El Sheikh", "Luxor", "Matrouh", "Menia", "Menofia", "North Sinai", "Port Said", "Qalubia", "Qena", "Sharqia", "Sixth of October", "Sohag", "South Sinai"],
    "El Salvador":[ "Ahuachapan", "Cabanas", "Chalatenango", "Cuscatlan", "La Libertad", "La Paz", "La Union", "Morazan", "San Miguel", "San Salvador", "San Vicente", "Santa Ana", "Sonsonate", "Usulutan"],
    "Equatorial Guinea":[ "Annobon", "Bioko Norte", "Bioko Sur", "Centro Sur", "Kie-Ntem", "Litoral", "Wele-Nzas"],
    "Eritrea":[ "Anseba", "Debub", "Debub-Keih-Bahri", "Gash-Barka", "Maekel", "Semien-Keih-Bahri"],
    "Estonia":[ "Harjumaa (Tallinn)", "Hiiumaa (Kardla)", "Ida-Virumaa (Johvi)", "Järvamaa (Paide)", "Jõgevamaa (Jogeva)", "Läänemaa", "Lääne-Virumaa (Rakvere)", "Pärnumaa (Parnu)", "Põlvamaa (Polva)", "Raplamaa (Rapla)", "Saaremaa (Kuessaare)", "Tartumaa (Tartu)", "Valgamaa (Valga)", "Viljandimaa (Viljandi)", "Võrumaa (Voru)"],
    "Ethiopia":[ "Addis Ababa", "Afar", "Amhara", "Benshangul-Gumaz", "Dire Dawa", "Gambela", "Harari", "Oromia", "Somali", "Southern Nations Nationalities and People's Region", "Tigray"],
    "Falkland Islands (Islas Malvinas)":[ "Falkland Islands (Islas Malvinas)"],
    "Faroe Islands":[ "Bordoy", "Eysturoy", "Mykines", "Sandoy", "Skuvoy", "Streymoy", "Suduroy", "Tvoroyri", "Vagar"],
    "Fiji":[ "Central", "Eastern", "Northern", "Rotuma", "Western"],
    "Finland":[ "Ahvenanmaan lääni", "Etelä-Suomen lääni", "Itä-Suomen lääni", "Länsi-Suomen lääni", "Lapin lääni", "Oulun lääni"],
    "France":[ "Alsace", "Aquitaine", "Auvergne", "Basse-Normandie", "Bourgogne", "Bretagne", "Centre", "Champagne-Ardenne", "Corse", "Franche-Comte", "Haute-Normandie", "Ile-de-France", "Languedoc-Roussillon", "Limousin", "Lorraine", "Midi-Pyrenees", "Nord-Pas-de-Calais", "Pays de la Loire", "Picardie", "Poitou-Charentes", "Provence-Alpes-Cote d'Azur", "Rhone-Alpes"],
    "French Guiana":[ "French Guiana"],
    "French Polynesia":[ "Archipel des Marquises", "Archipel des Tuamotu", "Archipel des Tubuai", "Iles du Vent", "Iles Sous-le-Vent"],
    "French Southern and Antarctic Lands":[ "Adelie Land", "Ile Crozet", "Iles Kerguelen", "Iles Saint-Paul et Amsterdam"],
    "Gabon":[ "Estuaire", "Haut-Ogooue", "Moyen-Ogooue", "Ngounie", "Nyanga", "Ogooue-Ivindo", "Ogooue-Lolo", "Ogooue-Maritime", "Woleu-Ntem"],
    "Gambia, The":[ "Banjul", "Central River", "Lower River", "North Bank", "Upper River", "Western"],
    "Georgia":[ "Abashis", "Abkhazia or Ap'khazet'is Avtonomiuri Respublika (Sokhumi)", "Adigenis", "Ajaria or Acharis Avtonomiuri Respublika (Bat'umi)", "Akhalgoris", "Akhalk'alak'is", "Akhalts'ikhis", "Akhmetis", "Ambrolauris", "Aspindzis", "Baghdat'is", "Bolnisis", "Borjomis", "Ch'khorotsqus", "Ch'okhatauris", "Chiat'ura", "Dedop'listsqaros", "Dmanisis", "Dushet'is", "Gardabanis", "Gori", "Goris", "Gurjaanis", "Javis", "K'arelis", "K'ut'aisi", "Kaspis", "Kharagaulis", "Khashuris", "Khobis", "Khonis", "Lagodekhis", "Lanch'khut'is", "Lentekhis", "Marneulis", "Martvilis", "Mestiis", "Mts'khet'is", "Ninotsmindis", "Onis", "Ozurget'is", "P'ot'i", "Qazbegis", "Qvarlis", "Rust'avi", "Sach'kheris", "Sagarejos", "Samtrediis", "Senakis", "Sighnaghis", "T'bilisi", "T'elavis", "T'erjolis", "T'et'ritsqaros", "T'ianet'is", "Tqibuli", "Ts'ageris", "Tsalenjikhis", "Tsalkis", "Tsqaltubo", "Vanis", "Zestap'onis", "Zugdidi", "Zugdidis"],
    "Germany":[ "Baden-Württemberg", "Bayern", "Berlin", "Brandenburg", "Bremen", "Hamburg", "Hessen", "Mecklenburg-Vorpommern", "Niedersachsen", "Nordrhein-Westfalen", "Rheinland-Pfalz", "Saarland", "Sachsen", "Sachsen-Anhalt", "Schleswig-Holstein", "Thüringen"],
    "Ghana":[ "Ashanti", "Brong-Ahafo", "Central", "Eastern", "Greater Accra", "Northern", "Upper East", "Upper West", "Volta", "Western"],
    "Gibraltar":[ "Gibraltar"],
    "Greece":[ "Aitolia kai Akarnania", "Akhaia", "Argolis", "Arkadhia", "Arta", "Attiki", "Ayion Oros (Mt. Athos)", "Dhodhekanisos", "Drama", "Evritania", "Evros", "Evvoia", "Florina", "Fokis", "Fthiotis", "Grevena", "Ilia", "Imathia", "Ioannina", "Irakleion", "Kardhitsa", "Kastoria", "Kavala", "Kefallinia", "Kerkyra", "Khalkidhiki", "Khania", "Khios", "Kikladhes", "Kilkis", "Korinthia", "Kozani", "Lakonia", "Larisa", "Lasithi", "Lesvos", "Levkas", "Magnisia", "Messinia", "Pella", "Pieria", "Preveza", "Rethimni", "Rodhopi", "Samos", "Serrai", "Thesprotia", "Thessaloniki", "Trikala", "Voiotia", "Xanthi", "Zakinthos"],
    "Greenland":[ "Avannaa (Nordgronland)", "Kitaa (Vestgronland)", "Tunu (Ostgronland)"],
    "Grenada":[ "Carriacou and Petit Martinique", "Saint Andrew", "Saint David", "Saint George", "Saint John", "Saint Mark", "Saint Patrick"],
    "Guadeloupe":[ "Basse-Terre", "Grande-Terre", "Iles de la Petite Terre", "Iles des Saintes", "Marie-Galante"],
    "Guam":[ "Guam"],
    "Guatemala":[ "Alta Verapaz", "Baja Verapaz", "Chimaltenango", "Chiquimula", "El Progreso", "Escuintla", "Guatemala", "Huehuetenango", "Izabal", "Jalapa", "Jutiapa", "Peten", "Quetzaltenango", "Quiche", "Retalhuleu", "Sacatepequez", "San Marcos", "Santa Rosa", "Solola", "Suchitepequez", "Totonicapan", "Zacapa"],
    "Guernsey":[ "Castel", "Forest", "St. Andrew", "St. Martin", "St. Peter Port", "St. Pierre du Bois", "St. Sampson", "St. Saviour", "Torteval", "Vale"],
    "Guinea":[ "Beyla", "Boffa", "Boke", "Conakry", "Coyah", "Dabola", "Dalaba", "Dinguiraye", "Dubreka", "Faranah", "Forecariah", "Fria", "Gaoual", "Gueckedou", "Kankan", "Kerouane", "Kindia", "Kissidougou", "Koubia", "Koundara", "Kouroussa", "Labe", "Lelouma", "Lola", "Macenta", "Mali", "Mamou", "Mandiana", "Nzerekore", "Pita", "Siguiri", "Telimele", "Tougue", "Yomou"],
    "Guinea-Bissau":[ "Bafata", "Biombo", "Bissau", "Bolama-Bijagos", "Cacheu", "Gabu", "Oio", "Quinara", "Tombali"],
    "Guyana":[ "Barima-Waini", "Cuyuni-Mazaruni", "Demerara-Mahaica", "East Berbice-Corentyne", "Essequibo Islands-West Demerara", "Mahaica-Berbice", "Pomeroon-Supenaam", "Potaro-Siparuni", "Upper Demerara-Berbice", "Upper Takutu-Upper Essequibo"],
    "Haiti":[ "Artibonite", "Centre", "Grand'Anse", "Nord", "Nord-Est", "Nord-Ouest", "Ouest", "Sud", "Sud-Est"],
    "Heard Island and McDonald Islands":[ "Heard Island and McDonald Islands"],
    "Holy See (Vatican City)":[ "Holy See (Vatican City)"],
    "Honduras":[ "Atlantida", "Choluteca", "Colon", "Comayagua", "Copan", "Cortes", "El Paraiso", "Francisco Morazan", "Gracias a Dios", "Intibuca", "Islas de la Bahia", "La Paz", "Lempira", "Ocotepeque", "Olancho", "Santa Barbara", "Valle", "Yoro"],
    "Hong Kong":[ "Hong Kong"],
    "Hungary":[ "Bacs-Kiskun", "Baranya", "Bekes", "Bekescsaba", "Borsod-Abauj-Zemplen", "Budapest", "Csongrad", "Debrecen", "Dunaujvaros", "Eger", "Fejer", "Gyor", "Gyor-Moson-Sopron", "Hajdu-Bihar", "Heves", "Hodmezovasarhely", "Jasz-Nagykun-Szolnok", "Kaposvar", "Kecskemet", "Komarom-Esztergom", "Miskolc", "Nagykanizsa", "Nograd", "Nyiregyhaza", "Pecs", "Pest", "Somogy", "Sopron", "Szabolcs-Szatmar-Bereg", "Szeged", "Szekesfehervar", "Szolnok", "Szombathely", "Tatabanya", "Tolna", "Vas", "Veszprem", "Veszprem", "Zala", "Zalaegerszeg"],
    "Iceland":[ "Akranes", "Akureyri", "Arnessysla", "Austur-Bardhastrandarsysla", "Austur-Hunavatnssysla", "Austur-Skaftafellssysla", "Borgarfjardharsysla", "Dalasysla", "Eyjafjardharsysla", "Gullbringusysla", "Hafnarfjordhur", "Husavik", "Isafjordhur", "Keflavik", "Kjosarsysla", "Kopavogur", "Myrasysla", "Neskaupstadhur", "Nordhur-Isafjardharsysla", "Nordhur-Mulasys-la", "Nordhur-Thingeyjarsysla", "Olafsfjordhur", "Rangarvallasysla", "Reykjavik", "Saudharkrokur", "Seydhisfjordhur", "Siglufjordhur", "Skagafjardharsysla", "Snaefellsnes-og Hnappadalssysla", "Strandasysla", "Sudhur-Mulasysla", "Sudhur-Thingeyjarsysla", "Vesttmannaeyjar", "Vestur-Bardhastrandarsysla", "Vestur-Hunavatnssysla", "Vestur-Isafjardharsysla", "Vestur-Skaftafellssysla"],
    "India":[ "Andaman and Nicobar Islands", "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chandigarh", "Chhattisgarh", "Dadra and Nagar Haveli", "Daman and Diu", "Delhi", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jammu and Kashmir", "Jharkhand", "Karnataka", "Kerala", "Lakshadweep", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Orissa", "Pondicherry", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Tripura", "Uttar Pradesh", "Uttaranchal", "West Bengal"],
    "Indonesia":[ "Aceh", "Bali", "Banten", "Bengkulu", "East Timor", "Gorontalo", "Jakarta Raya", "Jambi", "Jawa Barat", "Jawa Tengah", "Jawa Timur", "Kalimantan Barat", "Kalimantan Selatan", "Kalimantan Tengah", "Kalimantan Timur", "Kepulauan Bangka Belitung", "Kepulauan Riau", "Lampung", "Maluku", "Maluku Utara", "Nusa Tenggara Barat", "Nusa Tenggara Timur", "Papua", "Papua Barat", "Riau", "Sulawesi Selatan", "Sulawesi Tengah", "Sulawesi Tenggara", "Sulawesi Utara", "Sumatera Barat", "Sumatera Selatan", "Sumatera Utara", "Yogyakarta"],
    "Iran, Islamic Republic of":[ "Ardabil", "Azarbayjan-e Gharbi", "Azarbayjan-e Sharqi", "Bushehr", "Chahar Mahall va Bakhtiari", "Esfahan", "Fars", "Gilan", "Golestan", "Hamadan", "Hormozgan", "Ilam", "Kerman", "Kermanshah", "Khorasan", "Khuzestan", "Kohgiluyeh va Buyer Ahmad", "Kordestan", "Lorestan", "Markazi", "Mazandaran", "Qazvin", "Qom", "Semnan", "Sistan va Baluchestan", "Tehran", "Yazd", "Zanjan"],
    "Iraq":[ "Al Anbar", "Al Basrah", "Al Muthanna", "Al Qadisiyah", "An Najaf", "Arbil", "As Sulaymaniyah", "At Ta'mim", "Babil", "Baghdad", "Dahuk", "Dhi Qar", "Diyala", "Karbala'", "Maysan", "Ninawa", "Salah ad Din", "Wasit"],
    "Ireland":[ "Carlow", "Cavan", "Clare", "Cork", "Donegal", "Dublin", "Galway", "Kerry", "Kildare", "Kilkenny", "Laois", "Leitrim", "Limerick", "Longford", "Louth", "Mayo", "Meath", "Monaghan", "Offaly", "Roscommon", "Sligo", "Tipperary", "Waterford", "Westmeath", "Wexford", "Wicklow"],
    "Isle of Man":[ "Isle of Man"],
    "Israel":[ "Central", "Haifa", "Jerusalem", "Northern", "Southern", "Tel Aviv"],
    "Italy":[ "Abruzzo", "Basilicata", "Calabria", "Campania", "Emilia-Romagna", "Friuli-Venezia Giulia", "Lazio", "Liguria", "Lombardia", "Marche", "Molise", "Piemonte", "Puglia", "Sardegna", "Sicilia", "Toscana", "Trentino-Alto Adige", "Umbria", "Valle d'Aosta", "Veneto"],
    "Jamaica":[ "Clarendon", "Hanover", "Kingston", "Manchester", "Portland", "Saint Andrew", "Saint Ann", "Saint Catherine", "Saint Elizabeth", "Saint James", "Saint Mary", "Saint Thomas", "Trelawny", "Westmoreland"],
    "Japan":[ "Aichi", "Akita", "Aomori", "Chiba", "Ehime", "Fukui", "Fukuoka", "Fukushima", "Gifu", "Gumma", "Hiroshima", "Hokkaido", "Hyogo", "Ibaraki", "Ishikawa", "Iwate", "Kagawa", "Kagoshima", "Kanagawa", "Kochi", "Kumamoto", "Kyoto", "Mie", "Miyagi", "Miyazaki", "Nagano", "Nagasaki", "Nara", "Niigata", "Oita", "Okayama", "Okinawa", "Osaka", "Saga", "Saitama", "Shiga", "Shimane", "Shizuoka", "Tochigi", "Tokushima", "Tokyo", "Tottori", "Toyama", "Wakayama", "Yamagata", "Yamaguchi", "Yamanashi"],
    "Jersey":[ "Jersey"],
    "Jordan":[ "'Amman", "Ajlun", "Al 'Aqabah", "Al Balqa'", "Al Karak", "Al Mafraq", "At Tafilah", "Az Zarqa'", "Irbid", "Jarash", "Ma'an", "Madaba"],
    "Kazakhstan":[ "Almaty", "Aqmola", "Aqtobe", "Astana", "Atyrau", "Batys Qazaqstan", "Bayqongyr", "Mangghystau", "Ongtustik Qazaqstan", "Pavlodar", "Qaraghandy", "Qostanay", "Qyzylorda", "Shyghys Qazaqstan", "Soltustik Qazaqstan", "Zhambyl"],
    "Kenya":[ "Central", "Coast", "Eastern", "Nairobi Area", "North Eastern", "Nyanza", "Rift Valley", "Western"],
    "Kiribati":[ "Abaiang", "Abemama", "Aranuka", "Arorae", "Banaba", "Banaba", "Beru", "Butaritari", "Central Gilberts", "Gilbert Islands", "Kanton", "Kiritimati", "Kuria", "Line Islands", "Line Islands", "Maiana", "Makin", "Marakei", "Nikunau", "Nonouti", "Northern Gilberts", "Onotoa", "Phoenix Islands", "Southern Gilberts", "Tabiteuea", "Tabuaeran", "Tamana", "Tarawa", "Tarawa", "Teraina"],
    "Korea, Democratic People's Republic of":[ "Chagang-do (Chagang Province)", "Hamgyong-bukto (North Hamgyong Province)", "Hamgyong-namdo (South Hamgyong Province)", "Hwanghae-bukto (North Hwanghae Province)", "Hwanghae-namdo (South Hwanghae Province)", "Kaesong-si (Kaesong City)", "Kangwon-do (Kangwon Province)", "Namp'o-si (Namp'o City)", "P'yongan-bukto (North P'yongan Province)", "P'yongan-namdo (South P'yongan Province)", "P'yongyang-si (P'yongyang City)", "Yanggang-do (Yanggang Province)"],
    "Korea, Republic of":[ "Ch'ungch'ong-bukto", "Ch'ungch'ong-namdo", "Cheju-do", "Cholla-bukto", "Cholla-namdo", "Inch'on-gwangyoksi", "Kangwon-do", "Kwangju-gwangyoksi", "Kyonggi-do", "Kyongsang-bukto", "Kyongsang-namdo", "Pusan-gwangyoksi", "Soul-t'ukpyolsi", "Taegu-gwangyoksi", "Taejon-gwangyoksi", "Ulsan-gwangyoksi"],
    "Kuwait":[ "Al 'Asimah", "Al Ahmadi", "Al Farwaniyah", "Al Jahra'", "Hawalli"],
    "Kyrgyzstan":[ "Batken Oblasty", "Bishkek Shaary", "Chuy Oblasty (Bishkek)", "Jalal-Abad Oblasty", "Naryn Oblasty", "Osh Oblasty", "Talas Oblasty", "Ysyk-Kol Oblasty (Karakol)"],
    "Laos":[ "Vientiane", "Attapu!(Attopeu)", "Bokèo", "Bolikhamxai!(Borikhane)", "Champasak!(Champassak)", "Houaphan", "Khammouan", "Louang!Namtha", "Louangphabang!(Louang!Prabang)", "Oudômxai!(Oudomsai)", "Phôngsali!(Phong!Saly)", "Salavan!(Saravane)", "Savannakhét", "Vientiane", "Xaignabouli", "Xékong!(Sékong)", "Xiangkhoang!(Xieng!Khouang)", "Xaisômboun"],
    "Latvia":[ "Aizkraukles Rajons", "Aluksnes Rajons", "Balvu Rajons", "Bauskas Rajons", "Cesu Rajons", "Daugavpils", "Daugavpils Rajons", "Dobeles Rajons", "Gulbenes Rajons", "Jekabpils Rajons", "Jelgava", "Jelgavas Rajons", "Jurmala", "Kraslavas Rajons", "Kuldigas Rajons", "Leipaja", "Liepajas Rajons", "Limbazu Rajons", "Ludzas Rajons", "Madonas Rajons", "Ogres Rajons", "Preilu Rajons", "Rezekne", "Rezeknes Rajons", "Riga", "Rigas Rajons", "Saldus Rajons", "Talsu Rajons", "Tukuma Rajons", "Valkas Rajons", "Valmieras Rajons", "Ventspils", "Ventspils Rajons"],
    "Lebanon":[ "Beyrouth", "Ech Chimal", "Ej Jnoub", "El Bekaa", "Jabal Loubnane"],
    "Lesotho":[ "Berea", "Butha-Buthe", "Leribe", "Mafeteng", "Maseru", "Mohales Hoek", "Mokhotlong", "Qacha's Nek", "Quthing", "Thaba-Tseka"],
    "Liberia":[ "Bomi", "Bong", "Grand Bassa", "Grand Cape Mount", "Grand Gedeh", "Grand Kru", "Lofa", "Margibi", "Maryland", "Montserrado", "Nimba", "River Cess", "Sinoe"],
    "Libya":[ "Ajdabiya", "Al 'Aziziyah", "Al Fatih", "Al Jabal al Akhdar", "Al Jufrah", "Al Khums", "Al Kufrah", "An Nuqat al Khams", "Ash Shati'", "Awbari", "Az Zawiyah", "Banghazi", "Darnah", "Ghadamis", "Gharyan", "Misratah", "Murzuq", "Sabha", "Sawfajjin", "Surt", "Tarabulus", "Tarhunah", "Tubruq", "Yafran", "Zlitan"],
    "Liechtenstein":[ "Balzers", "Eschen", "Gamprin", "Mauren", "Planken", "Ruggell", "Schaan", "Schellenberg", "Triesen", "Triesenberg", "Vaduz"],
    "Lithuania":[ "Akmenes Rajonas", "Alytaus Rajonas", "Alytus", "Anyksciu Rajonas", "Birstonas", "Birzu Rajonas", "Druskininkai", "Ignalinos Rajonas", "Jonavos Rajonas", "Joniskio Rajonas", "Jurbarko Rajonas", "Kaisiadoriu Rajonas", "Kaunas", "Kauno Rajonas", "Kedainiu Rajonas", "Kelmes Rajonas", "Klaipeda", "Klaipedos Rajonas", "Kretingos Rajonas", "Kupiskio Rajonas", "Lazdiju Rajonas", "Marijampole", "Marijampoles Rajonas", "Mazeikiu Rajonas", "Moletu Rajonas", "Neringa Pakruojo Rajonas", "Palanga", "Panevezio Rajonas", "Panevezys", "Pasvalio Rajonas", "Plunges Rajonas", "Prienu Rajonas", "Radviliskio Rajonas", "Raseiniu Rajonas", "Rokiskio Rajonas", "Sakiu Rajonas", "Salcininku Rajonas", "Siauliai", "Siauliu Rajonas", "Silales Rajonas", "Silutes Rajonas", "Sirvintu Rajonas", "Skuodo Rajonas", "Svencioniu Rajonas", "Taurages Rajonas", "Telsiu Rajonas", "Traku Rajonas", "Ukmerges Rajonas", "Utenos Rajonas", "Varenos Rajonas", "Vilkaviskio Rajonas", "Vilniaus Rajonas", "Vilnius", "Zarasu Rajonas"],
    "Luxembourg":[ "Diekirch", "Grevenmacher", "Luxembourg"],
    "Macao":[ "Macao"],
    "Macedonia, Former Yugoslav Republic of":[ "Aracinovo", "Bac", "Belcista", "Berovo", "Bistrica", "Bitola", "Blatec", "Bogdanci", "Bogomila", "Bogovinje", "Bosilovo", "Brvenica", "Cair (Skopje)", "Capari", "Caska", "Cegrane", "Centar (SkopjeZupa", "Cesinovo", "Cucer-Sandevo", "Debar", "Delcevo", "Delogozdi", "Demir Hisar", "Demir Kapija", "Dobrusevo", "Dolna Banjica", "Dolneni", "Dorce Petrov (Skopje)Dzepciste", "Gazi Baba (Skopje)", "Gevgelija", "Gostivar", "Gradsko", "Ilinden", "Izvor", "Jegunovce", "Kamenjane", "Karbinci", "Karpos (Skopje)", "Kavadarci", "Kicevo", "Kisela Voda (lecevce", "Kocani", "Konce", "Kondovo", "Konopiste", "Kosel", "Kratovo", "Kriva rivogastani", "Krusevo", "Kuklis", "Kukurecani", "Kumanovo", "Labunista", "Lipkovo", "Lozovo", "Lukovo", "Makedonska Kamenica", "Makedonski Brod", "Mavrovi eista", "Miravci", "Mogila", "Murtino", "Negotino", "Negotino-Poloska", "Novaci", "Novo Selo", "Oblesevo", "Ohrid", "Orasac", "Orizari", "Oslomej", "Pehcevo", "Petrovec", "Plasnia", "Podares", "Prilepp", "Radovis", "Rankovce", "Resen", "Rosoman", "Rostusa", "Samokov", "Saraj", "Sipkovica", "Sopiste", "Sopotnika", "Srbinovo", "Star Dojran", "Staravina", "Staro e", "Stip", "Struga", "Strumica", "Studenicani", "Suto Orizari (Skopje)", "Sveti Nikole", "Tearce", "Tetovo", "Topolcani", "Valandovo", "Vasilevo", "Veles", "Velesta", "Vevcani", "Vinica", "Vitolistica", "Vrapciste", "Vratnica", "Vrutok", "Zajas", "Zelenikovo", "Zileno", "Zitose", "Zletovo", "Zrnovci"],
    "Madagascar":[ "Antananarivo", "Antsiranana", "Fianarantsoa", "Mahajanga", "Toamasina", "Toliara"],
    "Malawi":[ "Balaka", "Blantyre", "Chikwawa", "Chiradzulu", "Chitipa", "Dedza", "Dowa", "Karonga", "Kasungu", "Likoma", "Lilongwe", "Machinga (Kasupe)", "Mchinji", "Mulanje", "Mwanza", "Mzimba", "Nkhata Bay", "Nkhotakota", "Nsanje", "Ntcheu", "Ntchisi", "Phalombe", "Rumphi", "Salima", "Thyolo", "Zomba"],
    "Malaysia":[ "Johor", "Kedah", "Kelantan", "Labuan", "Melaka", "Negeri Sembilan", "Pahang", "Perak", "Perlis", "Pulau Pinang", "Sabah", "Sarawak", "Selangor", "Terengganu", "Wilayah Persekutuan"],
    "Maldives":[ "Alifu", "Baa", "Dhaalu", "Faafu", "Gaafu Alifu", "Gaafu Dhaalu", "Gnaviyani", "Haa Alifu", "Haa afu", "Laamu", "Lhaviyani", "Maale", "Meemu", "Noonu", "Raa", "Seenu", "Shaviyani", "Thaa", "Vaavu"],
    "Mali":[ "Gao", "Kayes", "Kidal", "Koulikoro", "Mopti", "Segou", "Sikasso", "Tombouctou"],
    "Malta":[ "Valletta"],
    "Marshall Islands":[ "Ailinginae", "Ailinglaplap", "Ailuk", "Arno", "Aur", "Bikar", "Bikini", "Bokak", "Ebon", "Enewetak", "Erikub", "Jabat", "Jaluit", "Jemo", "Kili", "Kwajalein", "Lae", "Lib", "Likiep", "Majuro", "Maloelap", "Mejitorik", "Namu", "Rongelap", "Rongrik", "Toke", "Ujae", "Ujelang", "Utirik", "Wotho", "Wotje"],
    "Martinique":[ "Martinique"],
    "Mauritania":[ "Adrar", "Assaba", "Brakna", "Dakhlet Nouadhibou", "Gorgol", "Guidimaka", "Hodh Ech Chargui", "Hodh El Gharbi", "Inchiri", "Nouakchott", "Tagant", "Tiris Zemmour", "Trarza"],
    "Mauritius":[ "Agalega Islands", "Black River", "Cargados Carajos Shoals", "Flacq", "Grand Port", "Moka", "Pamplemousses", "Plaines Wilhems", "Port Louis", "Riviere du odrigues", "Savanne"],
    "Mayotte":[ "Dzaoudzi", "Pamandzi", "Mamoudzou", "Dembeni", "Bandrélé", "Kani-Kéli", "Bouéni", "Chirongui", "Sada", "Ouangani", "Chiconi", "Tsingoni", "M'Tsangamouji", "Acoua", "Mtsamboro", "Bandraboua", "Koungou"],
    "Mexico":[ "Aguascalientes", "Baja California", "Baja California Sur", "Campeche", "Chiapas", "Chihuahua", "Coahuila de Zaragoza", "Colima", "Distrito Federal", "Durango", "Guanajuato", "Guerrero", "Hidalgo", "Jalisco", "Mexico", "Michoacan de Ocampo", "Morelos", "Nayarit", "Nuevo Leon", "Oaxaca", "Puebla", "Queretaro de Arteaga", "Quintana Roo", "San si", "Sinaloa", "Sonora", "Tabasco", "Tamaulipas", "Tlaxcala", "Veracruz-Llave", "Yucatan", "Zacatecas"],
    "Micronesia, Federated States of":[ "Chuuk (Truk)", "Kosrae", "Pohnpei", "Yap"],
    "Moldova":[ "Balti", "Cahul", "Chisinau", "Chisinau", "Dubasari", "Edinet", "Gagauzia", "Lapusna", "Orhei", "Soroca", "Tighina", "Ungheni"],
    "Monaco":[ "Fontvieille", "La Condamine", "Monaco-Ville", "Monte-Carlo"],
    "Mongolia":[ "Arhangay", "Bayan-Olgiy", "Bayanhongor", "Bulgan", "Darhan", "Dornod", "Dornogovi", "Dundgovi", "Dzavhan", "Erdenet", "Govi-tiy", "Hovd", "Hovsgol", "Omnogovi", "Ovorhangay", "Selenge", "Suhbaatar", "Tov", "Ulaanbaatar", "Uvs"],
    "Montenegro":[ "Andrijevica", "Bar", "Berane", "Bijelo Polje", "Budva", "Cetinje", "Danilovgrad", "Herceg Novi", "Kolašin", "Kotor", "Mojkovac", "Nikšić", "Plav", "Plužine", "Pljevlja", "Podgorica", "Golubovci", "Tuzi", "Rožaje", "Šavnik", "Tivat", "Ulcinj", "Žablja"],
    "Montserrat":[ "Saint Anthony", "Saint Georges", "Saint Peter's"],
    "Morocco":[ "Agadir", "Al Hoceima", "Azilal", "Ben Slimane", "Beni Mellal", "Boulemane", "Casablanca", "Chaouen", "El Jadida", "El Kelaa des Srarhna", "Er Essaouira", "Fes", "Figuig", "Guelmim", "Ifrane", "Kenitra", "Khemisset", "Khenifra", "Khouribga", "Laayoune", "Larache", "Marrakech", "Meknes", "Nador", "Ouarzazate", "Oujda", "Rabat-", "Settat", "Sidi Kacem", "Tan-Tan", "Tanger", "Taounate", "Taroudannt", "Tata", "Taza", "Tetouan", "Tiznit"],
    "Mozambique":[ "Cabo Delgado", "Gaza", "Inhambane", "Manica", "Maputo", "Nampula", "Niassa", "Sofala", "Tete", "Zambezia"],
    "Myanmar":[ "Ayeyarwady Region", "Bago Region", "Chin State", "Kachin State", "Kayah State", "Kayin State", "Magway Region", "Mandalay Region", "Mon State", "Rakhine State", "Shan State", "Sagaing Region", "Tanintharyi Region", "Yangon Region", "Naypyidaw Union Territory", "Danu Self-Administered Zone", "Kokang Self-Administered Zone", "Naga Self-Administered Zone", "Pa-O Self-Administered Zone", "Pa Laung Self-Administered Zone", "Wa Self-Administered Division"],
    "Namibia":[ "Caprivi", "Erongo", "Hardap", "Karas", "Khomas", "Kunene", "Ohangwena", "Okavango", "Omaheke", "Omusati", "Oshana", "Oshikoto", "Otjozondjupa"],
    "Nauru":[ "Aiwo", "Anabar", "Anetan", "Anibare", "Baiti", "Boe", "Buada", "Denigomodu", "Ewa", "Ijuw", "Meneng", "Nibok", "Uaboe", "Yaren"],
    "Nepal":[ "Bagmati", "Bheri", "Dhawalagiri", "Gandaki", "Janakpur", "Karnali", "Kosi", "Lumbini", "Mahakali", "Mechi", "Narayani", "Rapti", "Sagarmatha", "Seti"],
    "Netherlands":[ "Drenthe", "Flevoland", "Friesland", "Gelderland", "Groningen", "Limburg", "Noord-Brabant", "Noord-Holland", "Overijssel", "Utrecht", "Zeeland", "Zuid-Holland"],
    "New Caledonia":[ "Iles Loyaute", "Nord", "Sud"],
    "New Zealand":[ "Auckland (Tāmaki-makau-rau)", "Bay of Plenty (Te Moana a Toi Te Huatahi)", "Canterbury (Waitaha)", "Hawke's Bay (Te Matau a Māui)", "Manawatu-Wanganui (Manawatu Whanganui)", "Northland (Te Tai tokerau)", "Otago (Ō Tākou)", "Southland (Murihiku)", "Taranaki (Taranaki)", "Waikato", "Wellington (Te Whanga-nui-a-Tara)", "West Coast (Te Taihau ā uru)", "Gisborne District (Tūranga nui a Kiwa)", "Marlborough District", "Nelson City (Whakatū)", "Tasman District", "Chatham Islands Territory (Wharekauri)"],
    "Nicaragua":[ "Boaco", "Carazo", "Chinandega", "Chontales", "Estelí", "Granada", "Jinotega", "León", "Madriz", "Managua", "Masaya", "Matagalpa", "Nueva Segovia", "Río San Juan", "Rivas", "Atlántico Norte", "Atlántico Sur"],
    "Niger":[ "Agadez", "Diffa", "Dosso", "Maradi", "Niamey", "Tahoua", "Tillaberi", "Zinder"],
    "Nigeria":[ "Abia", "Abuja Federal Capital Territory", "Adamawa", "Akwa Ibom", "Anambra", "Bauchi", "Bayelsa", "Benue", "Borno", "Cross River", "Delta", "Ebonyi", "Edo", "Ekiti", "Enugu", "Gombe", "Imo", "Jigawa", "no", "Katsina", "Kebbi", "Kogi", "Kwara", "Lagos", "Nassarawa", "Niger", "Ogun", "Ondo", "Osun", "Oyo", "Plateau", "Rivers", "Sokoto", "Taraba", "Yobe", "Zamfara"],
    "Niue":[ "Niue"],
    "Norfolk Island":[ "Norfolk Island"],
    "Northern Mariana Islands":[ "Northern Islands", "Rota", "Saipan", "Tinian"],
    "Norway":[ "Akershus", "Aust-Agder", "Buskerud", "Finnmark", "Hedmark", "Hordaland", "Møre og Romsdal", "Nordland", "Nord-Trøndelag", "Oppland", "Oslo", "Rogaland", "Sogn og Fjordane", "Sør-Trøndelag", "Telemark", "Troms", "Vest-Agder", "Vestfold", "Østfold", "Jan Mayen", "Svalbard"],
    "Oman":[ "Ad Dakhiliyah", "Al Batinah", "Al Wusta", "Ash Sharqiyah", "Az Zahirah", "Masqat", "Musandam", "Zufar"],
    "Pakistan":[ "Balochistan", "Federally Administered Tribal Areas", "Islamabad Capital Territory", "North-West Frontier Province", "Punjab", "Sindh"],
    "Palau":[ "Aimeliik", "Airai", "Angaur", "Hatobohei", "Kayangel", "Koror", "Melekeok", "Ngaraard", "Ngarchelong", "Ngardmau", "Ngatpang", "Ngchesar", "Ngeremlengui", "Ngiwal", "Palau leliu", "Sonsoral", "Tobi"],
    "Palestine, State of":[ "Palestine"],
    "Panama":[ "Bocas del Toro", "Chiriqui", "Cocle", "Colon", "Darien", "Herrera", "Los Santos", "Panama", "San Blas", "Veraguas"],
    "Papua New Guinea":[ "Bougainville", "Central", "Chimbu", "East New Britain", "East Sepik", "Eastern Highlands", "Enga", "Gulf", "Madang", "Manus", "Milne Bay", "Morobe", "National Capital", "New orthern", "Sandaun", "Southern Highlands", "West New Britain", "Western", "Western Highlands"],
    "Paraguay":[ "Alto Paraguay", "Alto Parana", "Amambay", "Asuncion (city)", "Caaguazu", "Caazapa", "Canindeyu", "Central", "Concepcion", "Cordillera", "Guaira", "Itapua", "Misiones", "Neembucu", "Paraguari", "Presidente Hayes", "San Pedro"],
    "Peru":[ "Amazonas", "Ancash", "Apurimac", "Arequipa", "Ayacucho", "Cajamarca", "Callao", "Cusco", "Huancavelica", "Huanuco", "Ica", "Junin", "La Libertad", "Lambayeque", "Lima", "Loreto", "Madre de egua", "Pasco", "Piura", "Puno", "San Martin", "Tacna", "Tumbes", "Ucayali"],
    "Philippines":[ "Abra", "Agusan del Norte", "Agusan del Sur", "Aklan", "Albay", "Angeles", "Antique", "Aurora", "Bacolod", "Bago", "Baguio", "Bais", "Basilan", "Basilan an", "Batanes", "Batangas", "Batangas City", "Benguet", "Bohol", "Bukidnon", "Bulacan", "Butuan", "Cabanatuan", "Cadiz", "Cagayan", "Cagayan de Oro", "Calbayog", "Caloocan", "Camarines arines Sur", "Camiguin", "Canlaon", "Capiz", "Catanduanes", "Cavite", "Cavite City", "Cebu", "Cebu City", "Cotabato", "Dagupan", "Danao", "Dapitan", "Davao City Davao", "Davao del Sur", "Davao Dipolog", "Dumaguete", "Eastern Samar", "General Santos", "Gingoog", "Ifugao", "Iligan", "Ilocos Norte", "Ilocos Sur", "Iloilo", "Iloilo City", "Iriga", "Isabela", "Kalinga-Apayao", "La a Union", "Laguna", "Lanao del Norte", "Lanao del Sur", "Laoag", "Lapu-Lapu", "Legaspi", "Leyte", "Lipa", "Lucena", "Maguindanao", "Mandaue", "Manila", "Marawi", "Marinduque", "Masbate", "Mindoro l", "Mindoro Oriental", "Misamis Occidental", "Misamis Oriental", "Mountain", "Naga", "Negros Occidental", "Negros Oriental", "North Cotabato", "Northern Samar", "Nueva va Vizcaya", "Olongapo", "Ormoc", "Oroquieta", "Ozamis", "Pagadian", "Palawan", "Palayan", "Pampanga", "Pangasinan", "Pasay", "Puerto Princesa", "Quezon", "Quezon ino", "Rizal", "Romblon", "Roxas", "Samar", "San Carlos (in Negros Occidental)", "San Carlos (in Pangasinan)", "San Jose", "San Pablo", "Silay", "Siquijor", "Sorsogon", "South Southern Leyte", "Sultan Kudarat", "Sulu", "Surigao", "Surigao del Norte", "Surigao del Sur", "Tacloban", "Tagaytay", "Tagbilaran", "Tangub", "Tarlac", "Tawitawi", "Toledo", "Trece Zambales", "Zamboanga", "Zamboanga del Norte", "Zamboanga del Sur"],
    "Pitcairn":[ "Pitcairn Islands"],
    "Poland":[ "Dolnoslaskie", "Kujawsko-", "Lodzkie", "Lubelskie", "Lubuskie", "Malopolskie", "Mazowieckie", "Opolskie", "Podkarpackie", "Podlaskie", "Pomorskie", "Slaskie", "Swietokrzyskie", "Warminsko-", "Wielkopolskie", "Zachodniopomorskie"],
    "Portugal":[ "Acores (Azores)", "Aveiro", "Beja", "Braga", "Braganca", "Castelo Branco", "Coimbra", "Evora", "Faro", "Guarda", "Leiria", "Lisboa", "Madeira", "Portalegre", "Porto", "Santarem", "Setubal", "Viana o", "Vila Real", "Viseu"],
    "Puerto Rico":[ "Adjuntas", "Aguada", "Aguadilla", "Aguas Buenas", "Aibonito", "Anasco", "Arecibo", "Arroyo", "Barceloneta", "Barranquitas", "Bayamon", "Cabo Rojo", "Caguas", "Camuy", "Canovanas", "Carolina", "Cat", "Ceiba", "Ciales", "Cidra", "Coamo", "Comerio", "Corozal", "Culebra", "Dorado", "Fajardo", "Florida", "Guanica", "Guayama", "Guayanilla", "Guaynabo", "Gurabo", "Hatillo", "Hormigueros", "Humacao", "Isabe", "Juana Diaz", "Juncos", "Lajas", "Lares", "Las Marias", "Las oiza", "Luquillo", "Manati", "Maricao", "Maunabo", "Mayaguez", "Moca", "Morovis", "Naguabo", "Naranjito", "Orocovis", "Patillas", "Penuelas", "Ponce", "Quebradillas", "Rincon", "Rio Grande", "Sabana linas", "San German", "San Juan", "San Lorenzo", "San Sebastian", "Santa Isabel", "Toa Alta", "Toa Baja", "Trujillo Alto", "Utuado", "Vega Alta", "Vega ues", "Villalba", "Yabucoa", "Yauco"],
    "Qatar":[ "Ad Dawhah", "Al Ghuwayriyah", "Al Jumayliyah", "Al Khawr", "Al Wakrah", "Ar Rayyan", "Jarayan al Batinah", "Madinat ash Shamal", "Umm Salal"],
    "Réunion":[ "Réunion"],
    "Romania":[ "Alba", "Arad", "Arges", "Bacau", "Bihor", "Bistrita-Nasaud", "Botosani", "Braila", "Brasov", "Bucuresti", "Buzau", "Calarasi", "Caras-luj", "Constanta", "Covasna", "Dimbovita", "Dolj", "Galati", "Giurgiu", "Gorj", "Harghita", "Hunedoara", "Ialomita", "Iasi", "Maramures", "Mehedinti", "Mures", "Neamt", "Olt", "Prahova", "Salaj", "Satu u", "Suceava", "Teleorman", "Timis", "Tulcea", "Vaslui", "Vilcea", "Vrancea"],
    "Russian Federation":[ "Adygeya (Maykop)", "Aginskiy Buryatskiy (Aginskoye)", "Altay (Gorno-Altaysk)", "Altayskiy (Barnaul)", "Amurskaya (Blagoveshchensk)", "Astrakhanskaya", "Bashkortostan (Ufa)", "Belgorodskaya", "Bryanskaya", "Buryatiya (Ulan-Ude)", "Chechnya (Groznyy)", "Chelyabinskaya", "Chitinskaya", "Chukotskiy (Anadyr)", "Chuvashiya (Cheboksary)", "Dagestan (Makhachkala)", "Evenkiyskiy (Tura)", "Ingushetiya (Nazran')", "Irkutskaya", "Ivanovskaya", "Kabardino-Balkariya (Nal'chik)", "Kalmykiya (Elista)", "Kaluzhskaya", "Kamchatskaya (Petropavlovsk-Kamchatskiy)", "Karachayevo-Cherkesiya (Cherkessk)", "Kareliya (Petrozavodsk)", "Khabarovskiy", "Khakasiya (Abakan)", "Khanty-Mansiyskiy (Khanty-Mansiysk)", "Kirovskaya", "Komi (Syktyvkar)", "Komi-Permyatskiy (Kudymkar)", "Koryakskiy (Palana)", "Krasnodarskiy", "Krasnoyarskiy", "Kurganskaya", "Kurskaya", "Leningradskaya", "Lipetskaya", "Magadanskaya", "Mariy-El (Yoshkar-Ola)", "Mordoviya (Saransk)aya", "Moskva (Moscow)", "Murmanskaya", "Nenetskiy (Nar'yan-Mar)", "Nizhegorodskaya", "Novgorodskaya", "Novosibirskaya", "Omskaya", "Orenburgskaya", "Orlovskaya (Orel)", "Permskaya", "Primorskiy (Vladivostok)", "Pskovskaya", "Rostovskaya", "Ryazanskaya", "Sakha (Yakutsk)", "Sakhalinskaya (Yuzhno-Sakhalinsk)", "Samarskaya", "Leningradskaya", "Sankt-Peterburg (Saint Petersburg)", "Saratovskaya", "Severnaya Osetiya-Alaniya [North Ossetia] (Vladikavkaz)", "Smolenskaya", "Stavropol'skiy", "Sverdlovskaya (Yekaterinburg)aya", "Tatarstan (Kazan')", "Taymyrskiy (Dudinka)", "Tomskaya", "Tul'skaya", "Tverskaya", "Tyumenskaya", "Tyva (Kyzyl)", "Udmurtiya (Izhevsk)", "Ul'yanovskaya", "Ust'-Ordynskiy (Ust'-Ordynskiy)", "Vladimirskaya", "Volgogradskaya", "Vologodskaya", "Voronezhskaya", "Yamalo-Nenetskiy (Salekhard)", "Yaroslavskaya", "Yevreyskaya"],
    "Rwanda":[ "Kigali", "Eastern", "Northern", "Western", "Southern"],
    "Saint Barthélemy":[ "Au Vent", "Sous le Vent"],
    "Saint Helena, Ascension and Tristan da Cunha":[ "Ascension", "Saint Helena", "Tristan da Cunha"],
    "Saint Kitts and Nevis":[ "Christ Church Nichola Town", "Saint Anne Sandy Point", "Saint George Basseterre", "Saint George Gingerland", "Saint James Windward", "Saint John Capisterre", "Saint ree", "Saint Mary Cayon", "Saint Paul Capisterre", "Saint Paul Charlestown", "Saint Peter Basseterre", "Saint Thomas Lowland", "Saint Thomas Middle Island", "Trinity Point"],
    "Saint Lucia":[ "Anse-la-Raye", "Castries", "Choiseul", "Dauphin", "Dennery", "Gros Islet", "Laborie", "Micoud", "Praslin", "Soufriere", "Vieux Fort"],
    "Saint Martin (French part)":[ "Saint Martin"],
    "Saint Pierre and Miquelon":[ "Miquelon", "Saint Pierre"],
    "Saint Vincent and the Grenadines":[ "Charlotte", "Grenadines", "Saint-Andrew", "Saint-David", "Saint-George", "Saint-Patrick"],
    "Samoa":[ "A'ana", "Aiga-i-le-Tai", "Atua", "Fa'asaleleaga", "Gaga'emauga", "Gagaifomauga", "Palauli", "Satupa'itea", "Tuamasaga", "Va'a-o-Fonoti", "Vaisigano"],
    "San Marino":[ "Acquaviva", "Borgo Maggiore", "Chiesanuova", "Domagnano", "Faetano", "Fiorentino", "Monte Giardino", "San Marino", "Serravalle"],
    "Sao Tome and Principe":[ "Principe", "Sao Tome"],
    "Saudi Arabia":[ "'Asir", "Al Bahah", "Al Hudud ash Shamaliyah", "Al Jawf", "Al Madinah", "Al Qasim", "Ar Riyad", "Ash Sharqiyah (Eastern Province)", "Ha'il", "Jizan", "Makkah", "Najran", "Tabuk"],
    "Senegal":[ "Dakar", "Diourbel", "Fatick", "Kaolack", "Kolda", "Louga", "Saint-Louis", "Tambacounda", "Thies", "Ziguinchor"],
    "Serbia":[ "Beograd (Belgrade)", "Borski", "Braničevski", "Jablanički", "Južnobački", "Južnobanatski", "Kolubarski", "Kosovski", "Kosovsko-Mitrovački", "Kosovsko-Pomoravski", "Mačvanski", "Moravički", "Nišavski", "Pčinjski", "Pećki", "Pirotski", "Podunavski", "Pomoravski", "Prizrenski", "Rasinski", "Raški", "Severnobački", "Severnobanatski", "Srednjebanatski", "Sremski", "Šumadijski", "Toplički", "Zaječarski", "Zapadnobački", "Zlatiborski"],
    "Seychelles":[ "Anse aux Pins", "Anse Boileau", "Anse Etoile", "Anse Louis", "Anse Royale", "Baie Lazare", "Baie Sainte Anne", "Beau Vallon", "Bel Air", "Bel Ombre", "Cascade", "Glacis", "Grand' Anse ", "Grand' Anse (on Praslin)", "La Digue", "La Riviere Anglaise", "Mont Buxton", "Mont Fleuri", "Plaisance", "Pointe La Rue", "Port Glaud", "Saint Louis", "Takamaka"],
    "Sierra Leone":[ "Eastern", "Northern", "Southern", "Western"],
    "Singapore":[ "Central Singapore", "North East", "North West", "South East", "South West"],
    "Sint Maarten (Dutch part)":[ "Sint Maarten"],
    "Slovakia":[ "Banskobystricky", "Bratislavsky", "Kosicky", "Nitriansky", "Presovsky", "Trenciansky", "Trnavsky", "Zilinsky"],
    "Slovenia":[ "Ajdovscina", "Beltinci", "Bled", "Bohinj", "Borovnica", "Bovec", "Brda", "Brezice", "Brezovica", "Cankova-Tisina", "Celje", "Cerklje na Gorenjskem", "Cerknica", "Cerkno", "Crensovci", "Crna na Crnomelj", "Destrnik-Trnovska Vas", "Divaca", "Dobrepolje", "Dobrova-Horjul-Polhov Gradec", "Dol pri Ljubljani", "Domzale", "Dornava", "Dravograd", "Duplek", "Gorenja Vas-orisnica", "Gornja Radgona", "Gornji Grad", "Gornji Petrovci", "Grosuplje", "Hodos Salovci", "Hrastnik", "Hrpelje-Kozina", "Idrija", "Ig", "Ilirska Bistrica", "Ivancna ola", "Jesenice", "Jursinci", "Kamnik", "Kanal", "Kidricevo", "Kobarid", "Kobilje", "Kocevje", "Komen", "Koper", "Kozje", "Kranj", "Kranjska o", "Kungota", "Kuzma", "Lasko", "Lenart", "Lendava", "Litija", "Ljubljana", "Ljubno", "Ljutomer", "Logatec", "Loska Dolina", "Loski e", "Lukovica", "Majsperk", "Maribor", "Medvode", "Menges", "Metlika", "Mezica", "Miren-Kostanjevica", "Mislinja", "Moravce", "Moravske Toplice", "Mozirje", "Murska ta", "Naklo", "Nazarje", "Nova Gorica", "Novo Mesto", "Odranci", "Ormoz", "Osilnica", "Pesnica", "Piran", "Pivka", "Podcetrtek", "Podvelka-Ribnica", "Postojna", "Preddvor", "Ptuj", "Puconci", "Race-ce", "Radenci", "Radlje ob Dravi", "Radovljica", "Ravne-Prevalje", "Ribnica", "Rogasevci", "Rogaska Slatina", "Rogatec", "Ruse", "Semic", "Sencur", "Sentilj", "Sentjernej", "Sentjur pri nica", "Sezana", "Skocjan", "Skofja Loka", "Skofljica", "Slovenj Gradec", "Slovenska Bistrica", "Slovenske Konjice", "Smarje pri Jelsah", "Smartno ob anj", "Starse", "Store", "Sveti Jurij", "Tolmin", "Trbovlje", "Trebnje", "Trzic", "Turnisce", "Velenje", "Velike Lasce", "Videm", "Vipava", "Vitanje", "Vodice", "Vojnik", "Vrhnika", "Vuzenica", "Zagorje alec", "Zavrc", "Zelezniki", "Ziri", "Zrece"],
    "Solomon Islands":[ "Bellona", "Central", "Choiseul (Lauru)", "Guadalcanal", "Honiara", "Isabel", "Makira", "Malaita", "Rennell", "Temotu", "Western"],
    "Somalia":[ "Awdal", "Bakool", "Banaadir", "Bari", "Bay", "Galguduud", "Gedo", "Hiiraan", "Jubbada Dhexe", "Jubbada Hoose", "Mudug", "Nugaal", "Sanaag", "Shabeellaha Dhexe", "Shabeellaha l", "Togdheer", "Woqooyi Galbeed"],
    "South Africa":[ "Eastern Cape", "Free State", "Gauteng", "KwaZulu-Natal", "Limpopo", "Mpumalanga", "Northern Cape", "North West", "Western Cape"],
    "South Georgia and South Sandwich Islands":[ "Bird Island", "Bristol Island", "Clerke Rocks", "Montagu Island", "Saunders Island", "South Georgia", "Southern Thule", "Traversay Islands"],
    "South Sudan":[ "South Sudan"],
    "Spain":[ "Albacete", "Alicante", "Almería", "Araba/Álava", "Asturias", "Ávila", "Badajoz", "Barcelona", "Bizkaia", "Burgos", "Cáceres", "Cádiz", "Cantabria", "Castellón", "Cueta", "Ciudad Real", "Córdoba", "A Coruña", "Cuenca", "Gipuzkoa", "Girona", "Granada", "Guadalajara", "Huelva", "Huesca", "Illes Balears", "Jaén", "León", "Lleida", "Lugo", "Madrid", "Málaga", "Melilla", "Murcia", "Navarre", "Ourense", "Palencia", "Las Palmas", "Pontevedra", "La Rioja", "Salamanca", "Santa Cruz de Tenerife", "Segovia", "Sevilla", "Soria", "Tarragona", "Teruel", "Toledo", "Valencia", "Valladolid", "Zamora", "Zaragoza"],
    "Sri Lanka":[ "Central", "Eastern", "North Central", "North Eastern", "North Western", "Northern", "Sabaragamuwa", "Southern", "Uva", "Western"],
    "Sudan":[ "A'ali an Nil", "Al Bahr al Ahmar", "Al Buhayrat", "Al Jazirah", "Al Khartum", "Al Qadarif", "Al Wahdah", "An Nil al Abyad", "An Nil al Azraq", "Ash Shamaliyah", "Bahr al rb al Istiwa'iyah", "Gharb Bahr al Ghazal", "Gharb Darfur", "Gharb Kurdufan", "Janub Darfur", "Janub Kurdufan", "Junqali", "Kassala", "Nahr an Nil", "Shamal Bahr al amal Darfur", "Shamal Kurdufan", "Sharq al Istiwa'iyah", "Sinnar", "Warab"],
    "Suriname":[ "Brokopondo", "Commewijne", "Coronie", "Marowijne", "Nickerie", "Para", "Paramaribo", "Saramacca", "Sipaliwini", "Wanica"],
    "Svalbard and Jan Mayen":[ "Barentsoya", "Bjornoya", "Edgeoya", "Hopen", "Kvitoya", "Nordaustandet", "Prins Karls Forland", "Spitsbergen"],
    "Swaziland":[ "Hhohho", "Lubombo", "Manzini", "Shiselweni"],
    "Sweden":[ "Blekinge", "Dalarnas", "Gavleborgs", "Gotlands", "Hallands", "Jamtlands", "Jonkopings", "Kalmar", "Kronobergs", "Norrbottens", "Orebro", "Ostergotlands", "Skane", "Sodermanlands", "Stockholm", "Varmlands", "Vasterbottens", "Vasternorrlands", "Vastmanlands", "Vastra Gotalands"],
    "Switzerland":[ "Aargau", "Appenzell Ausserrhoden", "Appenzell Innerhoden", "Basel-Landschaft", "Basel-Stadt", "Bern", "Fribourg", "Genève", "Glarus", "Graubünden", "Jura", "Luzern", "Neuchâtel", "Nidwalden", "Obwalden", "Sankt Gallen", "Schaffhausen", "Schwyz", "Solothurn", "Thurgau", "Ticino", "Uri", "Valais", "Waadt", "Zug", "Zürich"],
    "Syrian Arab Republic":[ "Al Hasakah", "Al Ladhiqiyah", "Al Qunaytirah", "Ar Raqqah", "As Suwayda'", "Dar'a", "Dayr az Zawr", "Dimashq", "Halab", "Hamah", "Hims", "Idlib", "Rif Dimashq", "Tartus"],
    "Taiwan, Province of China":[ "Chang-hua", "Chi-lung", "Chia-i", "Chia-i", "Chung-hsing-hsin-ts'un", "Hsin-chu", "Hsin-chu", "Hua-lien", "I-lan", "Kao-hsiung", "Kao-hsiung", "Miao-li", "Nan-t'ou", "P'eng-hu", "P'ing--chung", "T'ai-chung", "T'ai-nan", "T'ai-nan", "T'ai-pei", "T'ai-pei", "T'ai-tung", "T'ao-yuan", "Yun-lin"],
    "Tajikistan":[ "Viloyati Khatlon", "Viloyati Leninobod", "Viloyati Mukhtori Kuhistoni Badakhshon"],
    "Tanzania, United Republic of":[ "Arusha", "Coast", "Dar es Salaam", "Dodoma", "Iringa", "Kagera", "Kigoma", "Kilimanjaro", "Lindi", "Manyara", "Mara", "Mbeya", "Morogoro", "Mtwara", "Mwanza", "Pemba North", "Pemba South", "Rukwa", "Ruvuma", "Shinyanga", "Singida", "Tabora", "Tanga", "Zanzibar North", "Zanzibar Central/South", "Zanzibar Urban/West"],
    "Thailand":[ "Amnat Charoen", "Ang Thong", "Buriram", "Chachoengsao", "Chai Nat", "Chaiyaphum", "Chanthaburi", "Chiang Mai", "Chiang Rai", "Chon Buri", "Chumphon", "Kalasin", "Kamphaeng hanaburi", "Khon Kaen", "Krabi", "Krung Thep Mahanakhon (Bangkok)", "Lampang", "Lamphun", "Loei", "Lop Buri", "Mae Hong Son", "Maha Sarakham", "Mukdahan", "Nakhon Nayok", "Nakhon khon Phanom", "Nakhon Ratchasima", "Nakhon Sawan", "Nakhon Si Thammarat", "Nan", "Narathiwat", "Nong Bua Lamphu", "Nong Khai", "Nonthaburi", "Pathum tani", "Phangnga", "Phatthalung", "Phayao", "Phetchabun", "Phetchaburi", "Phichit", "Phitsanulok", "Phra Nakhon Si Ayutthaya", "Phrae", "Phuket", "Prachin Buri", "Prachuap Khiri ng", "Ratchaburi", "Rayong", "Roi Et", "Sa Kaeo", "Sakon Nakhon", "Samut Prakan", "Samut Sakhon", "Samut Songkhram", "Sara Buri", "Satun", "Sing ket", "Songkhla", "Sukhothai", "Suphan Buri", "Surat Thani", "Surin", "Tak", "Trang", "Trat", "Ubon Ratchathani", "Udon Thani", "Uthai Thani", "Uttaradit", "Yala", "Yasothon"],
    "Timor-Leste":[ "Timor-Leste"],
    "Togo":[ "De La Kara", "Des Plateaux", "Des Savanes", "Du Centre", "Maritime"],
    "Tokelau":[ "Atafu", "Fakaofo", "Nukunonu"],
    "Tonga":[ "Ha'apai", "Tongatapu", "Vava'u"],
    "Trinidad and Tobago":[ "Arima", "Caroni", "Mayaro", "Nariva", "Port-of-Spain", "Saint Andrew", "Saint David", "Saint George", "Saint Patrick", "San Fernando", "Victoria", "Tobago"],
    "Tunisia":[ "Ariana", "Beja", "Ben Arous", "Bizerte", "El Kef", "Gabes", "Gafsa", "Jendouba", "Kairouan", "Kasserine", "Kebili", "Mahdia", "Medenine", "Monastir", "Nabeul", "Sfax", "Sidi Bou na", "Sousse", "Tataouine", "Tozeur", "Tunis", "Zaghouan"],
    "Turkey":[ "Adana", "Adiyaman", "Afyon", "Agri", "Aksaray", "Amasya", "Ankara", "Antalya", "Ardahan", "Artvin", "Aydin", "Balikesir", "Bartin", "Batman", "Bayburt", "Bilecik", "Bingol", "Bitlis", "Bolu", "Burdur", "Bursae", "Cankiri", "Corum", "Denizli", "Diyarbakir", "Duzce", "Edirne", "Elazig", "Erzincan", "Erzurum", "Eskisehir", "Gaziantep", "Giresun", "Gumushane", "Hakkari", "Hatay", "Icel", "Igdir", "Isparta", "IstanbKahramanmaras", "Karabuk", "Karaman", "Kars", "Kastamonu", "Kayseri", "Kilis", "Kirikkale", "Kirklareli", "Kirsehir", "Kocaeli", "Konya", "Kutahya", "Malatya", "Manisa", "Mardin", "Mugla", "Mus", "NevsehOrdu", "Osmaniye", "Rize", "Sakarya", "Samsun", "Sanliurfa", "Siirt", "Sinop", "Sirnak", "Sivas", "Tekirdag", "Tokat", "Trabzon", "Tunceli", "Usak", "Van", "Yalova", "Yozgat", "Zonguldak"],
    "Turkmenistan":[ "Ahal Welayaty", "Balkan Welayaty", "Dashhowuz Welayaty", "Lebap Welayaty", "Mary Welayaty"],
    "Turks and Caicos Islands":[ "Turks and Caicos Islands"],
    "Tuvalu":[ "Tuvalu"],
    "Uganda":[ "Abim", "Adjumani", "Amolatar", "Amuria", "Amuru", "Apac", "Arua", "Budaka", "Bududa", "Bugiri", "Bukedea", "Bukwa", "Buliisa", "Bundibugyo", "Bushenyi", "Busia", "Butaleja", "Dokolo", "Gulu", "Hoima", "Ibanda", "Iganga", "Isingiro", "Jinja", "Kaabong", "Kabale", "Kabarole", "Kaberamaido", "Kalangala", "Kaliro", "Kampala", "Kamuli", "Kamwenge", "Kanungu", "Kapchorwa", "Kasese", "Katakwi", "Kayunga", "Kibaale", "Kiboga", "Kiruhura", "Kisoro", "Kitgum", "Koboko", "Kotido", "Kumi", "Kyenjojo", "Lira", "Luwero", "Lyantonde", "Manafwa", "Maracha", "Masaka", "Masindi", "Mayuge", "Mbale", "Mbarara", "Mityana", "Moroto", "Moyo", "Mpigi", "Mubende", "Mukono", "Nakapiripirit", "Nakaseke", "Nakasongola", "Namutumba", "Nebbi", "Ntungamo", "Oyam", "Pader", "Pallisa", "Rakai", "Rukungiri", "Sembabule", "Sironko", "Soroti", "Tororo", "Wakiso", "Yumbe"],
    "Ukraine":[ "Cherkasy", "Chernihiv", "Chernivtsi", "Dnipropetrovsk", "Donetsk", "Ivano-Frankivsk", "Kharkiv", "Kherson", "Khmelnytskyi", "Kiev", "Kirovohrad", "Luhansk", "Lviv", "Mykolaiv", "Odessa", "Poltava", "Rivne", "Sumy", "Ternopil", "Vinnytsia", "Volyn", "Zakarpattia", "Zaporizhia", "Zhytomyr", "Avtonomna Respublika Krym", "Kyïv", "Sevastopol"],
    "United Arab Emirates":[ "Abu Dhabi", "Ajman", "Dubai", "Fujairah", "Ras al Khaimah", "Sharjah", "Umm Al Quwain"],
    "United Kingdom":[ "Avon", "Bedfordshire", "Berkshire", "Bristol, City of", "Buckinghamshire", "Cambridgeshire", "Cheshire", "Cleveland", "Cornwall", "Cumbria", "Derbyshire", "Devon", "Dorset", "Durham", "East Sussex", "Essex", "Gloucestershire", "Greater London", "Greater Manchester", "Hampshire (County of Southampton)", "Hereford and Worcester", "Herefordshire", "Hertfordshire", "Isle of Wight", "Kent", "Lancashire", "Leicestershire", "Lincolnshire", "London", "Merseyside", "Middlesex", "Norfolk", "Northamptonshire", "Northumberland", "North Humberside", "North Yorkshire", "Nottinghamshire", "Oxfordshire", "Rutland", "Shropshire", "Somerset", "South Humberside", "South Yorkshire", "Staffordshire", "Suffolk", "Surrey", "Tyne and Wear", "Warwickshire", "West Midlands", "West Sussex", "West Yorkshire", "Wiltshire", "Worcestershire", "Antrim", "Armagh", "Belfast, City of", "Down", "Fermanagh", "Londonderry", "Derry, City of", "Tyrone", "Aberdeen, City of", "Aberdeenshire", "Angus (Forfarshire)", "Argyll", "Ayrshire", "Banffshire", "Berwickshire", "Bute", "Caithness", "Clackmannanshire", "Cromartyshire", "Dumfriesshire", "Dunbartonshire (Dumbarton)", "Dundee, City of", "East Lothian (Haddingtonshire)", "Edinburgh, City of", "Fife", "Glasgow, City of", "Inverness-shire", "Kincardineshire", "Kinross-shire", "Kirkcudbrightshire", "Lanarkshire", "Midlothian (County of Edinburgh)", "Moray (Elginshire)", "Nairnshire", "Orkney", "Peeblesshire", "Perthshire", "Renfrewshire", "Ross and Cromarty", "Ross-shire", "Roxburghshire", "Selkirkshire", "Shetland (Zetland)", "Stirlingshire", "Sutherland", "West Lothian (Linlithgowshire)", "Wigtownshire", "Clwyd", "Dyfed", "Gwent", "Gwynedd", "Mid Glamorgan", "Powys", "South Glamorgan", "West Glamorgan"],
    "United Kingdom Overseas Territories":[   "Anguilla", "Bermuda", "British Virgin Islands", "Cayman Islands", "Falkland Islands", "Gibraltar", "Montserrat", "St Helena", "Tristan Da Cunha", "Turks & Caicos Islands"],
    "United States":[ "Alaska", "Alabama", "American Samoa", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "District of Columbia", "Micronesia", "Florida", "Georgia", "Guam", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Marshall Islands", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Northern Mariana Islands", "Ohio", "Oklahoma", "Oregon", "Palau", "Pennsylvania", "Puerto Rico", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virgin Islands", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming", "Armed Forces Americas", "Armed Forces Europe, Canada, Africa and Middle East", "Armed Forces Pacific"],
    "United States Minor Outlying Islands":[ "Baker Island", "Howland Island", "Jarvis Island", "Johnston Atoll", "Kingman Reef", "Midway Islands", "Navassa Island", "Palmyra Atoll", "Wake Island", "Bajo Nuevo Bank", "Serranilla Bank"],
    "Uruguay":[ "Artigas", "Canelones", "Cerro Largo", "Colonia", "Durazno", "Flores", "Florida", "Lavalleja", "Maldonado", "Montevideo", "Paysandú", "Río Negro", "Rivera", "Rocha", "Salto", "San José", "Soriano", "Tacuarembó", "Treinta y Tres"],
    "Uzbekistan":[ "Toshkent shahri", "Andijon", "Buxoro", "Farg‘ona", "Jizzax", "Namangan", "Navoiy", "Qashqadaryo (Qarshi)", "Samarqand", "Sirdaryo (Guliston)", "Surxondaryo (Termiz)", "Toshkent wiloyati", "Xorazm (Urganch)", "Qoraqalpog‘iston Respublikasi (Nukus)"],
    "Vanuatu":[ "Malampa", "Pénama", "Sanma", "Shéfa", "Taféa", "Torba"],
    "Venezuela, Bolivarian Republic of":[ "Dependencias Federales", "Distrito Federal", "Amazonas", "Anzoátegui", "Apure", "Aragua", "Barinas", "Bolívar", "Carabobo", "Cojedes", "Delta Amacuro", "Falcón", "Guárico", "Lara", "Mérida", "Miranda", "Monagas", "Nueva Esparta", "Portuguesa", "Sucre", "Táchira", "Trujillo", "Vargas", "Yaracuy", "Zulia"],
    "Viet Nam":[ "Đồng Nai", "Đồng Tháp", "Gia Lai", "Hà Giang", "Hà Nam", "Hà Tây", "Hà Tĩnh", "Hải Dương", "Hậu Giang", "Hòa Bình", "Hưng Yên", "Khánh Hòa", "Kiên Giang", "Kon Tum", "Lai Châu", "Lâm Đồng", "Lạng Sơn", "Lào Cai", "Long An", "Nam Định", "Nghệ An", "Ninh Bình", "Ninh Thuận", "Phú Thọ", "Phú Yên", "Quảng Bình", "Quảng Nam", "Quảng Ngãi", "Quảng Ninh", "Quảng Trị", "Sóc Trăng", "Sơn La", "Tây Ninh", "Thái Bình", "Thái Nguyên", "Thanh Hóa", "Thừa Thiên–Huế", "Tiền Giang", "Trà Vinh", "Tuyên Quang", "Vĩnh Long", "Vĩnh Phúc", "Yên Bái", "Cần Thơ", "Đà Nẵng", "Hà Nội", "Hải Phòng", "Hồ Chí Minh (Sài Gòn)"],
    "Virgin Islands, British":[ "Anegada", "Jost Van Dyke", "Tortola", "Virgin Gorda"],
    "Virgin Islands, U.S.":[ "St. Thomas", "St. John", "St. Croix"],
    "Wallis and Futuna":[ "Alo", "Sigave", "Wallis"],
    "Western Sahara":[ "Es Smara", "Boujdour", "Laâyoune", "Aousserd", "Oued ed Dahab"],
    "Yemen":[ "Şan‘ā'", "Abyān", "'Adan", "Aḑ Ḑāli'", "Al Bayḑā'", "Al Ḩudaydah", "Al Jawf", "Al Mahrah", "Al Maḩwīt", "'Amrān", "Dhamār", "Ḩaḑramawt", "Ḩajjah", "Ibb", "Laḩij", "Ma'rib", "Raymah", "Şā‘dah", "Şan‘ā'", "Shabwah", "Tā‘izz"],
    "Zambia":[ "Central", "Copperbelt", "Eastern", "Luapula", "Lusaka", "Northern", "North-Western", "Southern", "Western"],
    "Zimbabwe":[ "Bulawayo", "Harare", "Manicaland", "Mashonaland Central", "Mashonaland East", "Mashonaland West", "Masvingo", "Matabeleland North", "Matabeleland South", "Midlands"]
  };
});
